(in-package :fonts)

(defmethod parse-table ((table hhea-table))
  (setf (hhea-table-major-version table)
        (parse-uint16 "majorVersion"))
  (setf (hhea-table-minor-version table)
        (parse-uint16 "minorVersion"))
  (setf (hhea-table-ascender table)
        (parse-fword "ascender"))
  (setf (hhea-table-descender table)
        (parse-fword "descender"))
  (setf (hhea-table-line-gap table)
        (parse-fword "lineGap"))
  (setf (hhea-table-advance-width-max table)
        (parse-ufword "advanceWidthMax"))
  (setf (hhea-table-min-left-side-bearing table)
        (parse-fword "minLeftSideBearing"))
  (setf (hhea-table-min-right-side-bearing table)
        (parse-fword "minRightSideBearing"))
  (setf (hhea-table-x-max-extent table)
        (parse-fword "xMaxExtent"))
  (setf (hhea-table-caret-slope-rise table)
        (parse-int16 "caretSlopeRise"))
  (setf (hhea-table-caret-slope-run table)
        (parse-int16 "caretSlopeRun"))
  (setf (hhea-table-caret-offset table)
        (parse-int16 "caretOffset"))
  (parse-int16 "reserved")
  (parse-int16 "reserved")
  (parse-int16 "reserved")
  (parse-int16 "reserved")
  (setf (hhea-table-metric-data-format table)
        (parse-int16 "metricDataFormat"))
  (setf (hhea-table-number-of-hmetrics table)
        (parse-uint16 "numberOfHMetrics")))
