version: "3"
services:
  postgresql:
    image: "postgres:15"
    command: >
      postgres -c "shared_buffers=1GB"
               -c "max_connections=40"
               -c "log_statement=all"
    container_name: "tungsten-postgresql"
    ports: ["5432:5432"]
    volumes:
      - "postgresql-data:/var/lib/postgresql/data:rw"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    logging: &logging
      driver: "json-file"
      options:
        max-size: "10m"
volumes:
  postgresql-data:
