version: "3"
services:
  postgresql:
    image: "postgres:15"
    command: >
      postgres -c "shared_buffers=1GB"
               -c "max_connections=40"
               -c "log_statement=all"
               -c "ssl=on"
               -c "ssl_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem"
               -c "ssl_key_file=/etc/ssl/private/ssl-cert-snakeoil.key"
    container_name: "tungsten-postgresql"
    ports: ["5432:5432"]
    volumes:
      - "postgresql-data:/var/lib/postgresql/data:rw"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    logging: &logging
      driver: "json-file"
      options:
        max-size: "10m"
  influxdb:
    image: "influxdb:1.8"
    container_name: "tungsten-influxdb"
    ports: ["8086:8086"]
    volumes:
      - "./docker-compose/influxdb:/docker-entrypoint-initdb.d:ro"
      - "influxdb-data:/var/lib/influxdb:rw"
    environment:
      INFLUXDB_REPORTING_DISABLED: "true"
    logging: *logging
  grafana:
    image: "grafana/grafana:9.3.6"
    container_name: "tungsten-grafana"
    user: "root"
    ports: ["3000:3000"]
    volumes:
      - "./docker-compose/grafana/provisioning:/etc/grafana/provisioning:ro"
      - "grafana-data:/var/lib/grafana:rw"
    logging: *logging
volumes:
  postgresql-data:
  influxdb-data:
  grafana-data:
