(in-package :postgresql-test)

(deftest client/stress ()
  (let ((postgresql:*connection-acquisition-timeout* 1.0)
        (test-duration 1.0)
        (nb-threads 32)
        (max-connections 4)
        (sleep-duration 0.05)
        (threads nil)
        (mutex (system:make-mutex :name "postgresql-client-test"))
        (stoppingp nil))
    (with-test-client (:max-connections max-connections)
      (unwind-protect
           (flet ((main (client)
                    (lambda ()
                      (do ((postgresql:*client* client))
                          ((system:with-mutex (mutex) stoppingp)
                           nil)
                        (postgresql:query "SELECT 42")
                        (sleep sleep-duration)))))
             (dotimes (i nb-threads)
               (push (system:make-thread
                      (format nil "postgresql-test-client/~2,'0D" (1+ i))
                      (main postgresql:*client*))
                     threads))
             (sleep test-duration)
             (system:with-mutex (mutex)
               (setf stoppingp t)))
        (mapc 'system:join-thread threads)))))
