(in-package :core)

(define-condition unknown-binary-type (error)
  ((type
    :initarg :type))
  (:report
   (lambda (condition stream)
     (with-slots (type) condition
       (format stream "Unknown binary type ~S." type)))))

(defmacro define-binref-integer-functions (type-size signed-p endianness)
  (let* ((nb-octets type-size)
         (nb-bits (* nb-octets 8))
         (suffix (format nil "~:[U~;~]INT~D~@[~A~]" signed-p nb-bits
                         (case endianness
                           (:big-endian "BE")
                           (:little-endian "LE"))))
         (read-function
           (intern (concatenate 'string "BINREF-READ/" suffix)))
         (write-function
           (intern (concatenate 'string "BINREF-WRITE/" suffix))))
    `(progn
       (declaim (ftype (function (octet-vector (integer 0))
                                 (,(if signed-p 'signed-byte 'unsigned-byte)
                                   ,nb-bits))
                       ,read-function)
                (inline ,read-function))
       (defun ,read-function (octets offset)
         (declare (type octet-vector octets)
                  (type (integer 0) offset))
         (let ((value 0))
           ,@(let (forms)
               (dotimes (i nb-octets (nreverse forms))
                 (push `(setf (ldb (byte 8 ,(if (eq endianness :big-endian)
                                                (* (- nb-octets i 1) 8)
                                                (* i 8)))
                                   value)
                              (aref octets (+ offset ,i)))
                       forms)))
           ,(if signed-p
                `(if (logbitp ,(1- nb-bits) value)
                     (- value ,(ash 1 nb-bits))
                     value)
                'value)))
       (declaim (ftype (function ((,(if signed-p 'signed-byte 'unsigned-byte)
                                    ,nb-bits)
                                  octet-vector (integer 0)))
                       ,write-function)
                (inline ,write-function))
       (defun ,write-function (value octets offset)
         (declare (type (,(if signed-p 'signed-byte 'unsigned-byte) ,nb-bits)
                        value)
                  (type octet-vector octets)
                  (type (integer 0) offset))
         (let ((unsigned-value ,(if signed-p
                                    `(if (< value 0)
                                         (+ value ,(ash 1 nb-bits))
                                         value)
                                    'value)))
           ,@(let (forms)
               (dotimes (i nb-octets (nreverse forms))
                 (push `(setf (aref octets (+ offset ,i))
                              (ldb (byte 8 ,(if (eq endianness :big-endian)
                                                (* (- nb-octets i 1) 8)
                                                (* i 8)))
                                   unsigned-value))
                       forms)))
           ,(when signed-p
              `(when (< value 0)
                 (setf (ldb (byte 1 7)
                            (aref octets ,(if (eq endianness :big-endian)
                                              `offset
                                              `(+ offset ,(1- nb-octets)))))
                       1)))
           value)))))

(define-binref-integer-functions 1 t nil)
(define-binref-integer-functions 1 nil nil)
(define-binref-integer-functions 2 t :big-endian)
(define-binref-integer-functions 2 nil :big-endian)
(define-binref-integer-functions 2 t :little-endian)
(define-binref-integer-functions 2 nil :little-endian)
(define-binref-integer-functions 4 t :big-endian)
(define-binref-integer-functions 4 nil :big-endian)
(define-binref-integer-functions 4 t :little-endian)
(define-binref-integer-functions 4 nil :little-endian)
(define-binref-integer-functions 8 t :big-endian)
(define-binref-integer-functions 8 nil :big-endian)
(define-binref-integer-functions 8 t :little-endian)
(define-binref-integer-functions 8 nil :little-endian)

(defun binref-read-function (type)
  (case type
    (:int8     'binref-read/int8)
    (:uint8    'binref-read/uint8)
    (:int16be  'binref-read/int16be)
    (:int16le  'binref-read/int16le)
    (:uint16be 'binref-read/uint16be)
    (:uint16le 'binref-read/uint16le)
    (:int32be  'binref-read/int32be)
    (:int32le  'binref-read/int32le)
    (:uint32be 'binref-read/uint32be)
    (:uint32le 'binref-read/uint32le)
    (:int64be  'binref-read/int64be)
    (:int64le  'binref-read/int64le)
    (:uint64be 'binref-read/uint64be)
    (:uint64le 'binref-read/uint64le)
    (t (error 'unknown-binary-type :type type))))

(defun binref-write-function (type)
  (ecase type
    (:int8     'binref-write/int8)
    (:uint8    'binref-write/uint8)
    (:int16be  'binref-write/int16be)
    (:int16le  'binref-write/int16le)
    (:uint16be 'binref-write/uint16be)
    (:uint16le 'binref-write/uint16le)
    (:int32be  'binref-write/int32be)
    (:int32le  'binref-write/int32le)
    (:uint32be 'binref-write/uint32be)
    (:uint32le 'binref-write/uint32le)
    (:int64be  'binref-write/int64be)
    (:int64le  'binref-write/int64le)
    (:uint64be 'binref-write/uint64be)
    (:uint64le 'binref-write/uint64le)
    (t (error 'unknown-binary-type :type type))))

(defun binref-type-size (type)
  (ecase type
    ((:int8 :uint8)
     1)
    ((:int16be :int16le :uint16be :uint16le)
     2)
    ((:int32be :int32le :uint32be :uint32le)
     4)
    ((:int64be :int64le :uint64be :uint64le)
     8)
    (t
     (error 'unknown-binary-type :type type))))

(defun binref (type octets &optional (offset 0))
  (declare (type keyword type)
           (type octet-vector octets))
  (funcall (binref-read-function type) octets offset))

(define-compiler-macro binref (&whole form type octets &optional (offset 0))
  (if (constantp type)
      (let ((octets-var (gensym "OCTETS-"))
            (offset-var (gensym "OFFSET-")))
        `(let* ((,octets-var ,octets)
                (,offset-var ,offset))
           (,(binref-read-function type) ,octets-var ,offset-var)))
      form))

(defsetf binref (type octets &optional (offset 0)) (value)
  (if (constantp type)
      (let ((octets-var (gensym "OCTETS-"))
            (offset-var (gensym "OFFSET-")))
        `(let* ((,octets-var ,octets)
                (,offset-var ,offset))
           (,(binref-write-function type) ,value ,octets-var ,offset-var)))
      `(funcall (binref-write-function ,type) ,value ,octets ,offset)))

