(in-package :core-test)

(defmacro check-buffer-equal (octets buffer)
  (let ((buffer-var (gensym "BUFFER-")))
    `(let ((,buffer-var ,buffer))
       (check-equalp ,(core:octet-vector octets)
                     (subseq (core:buffer-data ,buffer-var)
                             (core:buffer-start ,buffer-var)
                             (core:buffer-end ,buffer-var))))))

(deftest buffer ()
  (let ((buffer (core:make-buffer 4)))
    (check-buffer-equal #() buffer)
    (core:buffer-reset buffer)
    (check-buffer-equal #() buffer)
    (core:buffer-append-octet buffer 1)
    (check-buffer-equal #(1) buffer)
    (core:buffer-append-octet buffer 2)
    (check-buffer-equal #(1 2) buffer)
    (core:buffer-skip buffer 1)
    (check-buffer-equal #(2) buffer)
    (core:buffer-append-octet buffer 3)
    (core:buffer-append-octet buffer 4)
    (core:buffer-skip buffer 3)
    (check-buffer-equal #() buffer)
    (core:buffer-append-octets buffer (core:octet-vector* 1 2))
    (check-buffer-equal #(1 2) buffer)
    (core:buffer-append-octets buffer (core:octet-vector* 3 4))
    (check-buffer-equal #(1 2 3 4) buffer)
    (core:buffer-skip buffer 3)
    (check-buffer-equal #(4) buffer)
    (core:buffer-append-octets buffer (core:octet-vector* 5 6))
    (check-buffer-equal #(4 5 6) buffer)
    (core:buffer-append-octets buffer (core:octet-vector* 7 8 9))
    (check-buffer-equal #(4 5 6 7 8 9) buffer)))

(deftest buffer-starts-with-octet ()
  (let ((buffer (core:make-buffer 32)))
    (check-false (core:buffer-starts-with-octet buffer 1))
    (core:buffer-append-octet buffer 1)
    (check-true (core:buffer-starts-with-octet buffer 1))
    (core:buffer-append-octet buffer 2)
    (core:buffer-append-octet buffer 3)
    (core:buffer-skip buffer 1)
    (check-true (core:buffer-starts-with-octet buffer 2))))

(deftest buffer-starts-with-octets ()
  (let ((buffer (core:make-buffer 32)))
    (check-false
     (core:buffer-starts-with-octets buffer (core:octet-vector* 1 2 3)))
    (core:buffer-append-octet buffer 1)
    (check-false
     (core:buffer-starts-with-octets buffer (core:octet-vector* 1 2 3)))
    (core:buffer-append-octet buffer 2)
    (core:buffer-append-octet buffer 3)
    (check-true
     (core:buffer-starts-with-octets buffer (core:octet-vector* 1 2 3)))
    (core:buffer-skip buffer 1)
    (check-false
     (core:buffer-starts-with-octets buffer (core:octet-vector* 1 2 3)))
    (check-true
     (core:buffer-starts-with-octets buffer (core:octet-vector* 2 3)))
    (core:buffer-append-octet buffer 4)
    (check-true
     (core:buffer-starts-with-octets buffer (core:octet-vector* 2 3)))))
