#!/bin/sh

set -eu
set -o pipefail

__die() {
    printf "$*\n" >&2
    exit 1
}

__usage() {
    exit_code=$1

    cat >&2 <<EOF
Usage: $0 [-h] <script>

ARGUMENTS

script               the path of the script to execute

OPTIONS

-h                   print help and exit
-i <implementation>  the implementation to use (default: $implementation)
EOF

    exit $exit_code
}

root=$(realpath $(dirname $0)/..)

implementation=sbcl

OPTIND=1
while getopts "hi:" arg; do
    case "$arg" in
        h) __usage 0 ;;
        i) implementation=$OPTARG ;;
        ?) __die "Unknown option '-$arg'" ;;
    esac
done
shift $((OPTIND - 1))

if [ $# -lt 1 ]; then
    __die "missing argument"
fi

script=$1

case "$implementation" in
    ccl)
        ccl --no-init --batch --quiet \
            --load $root/initialize.lisp \
            --load $script
        ;;

    sbcl)
        sbcl --noinform --no-sysinit --no-userinit --disable-debugger \
             --load $root/initialize.lisp \
             --script $script
        ;;

    *)
        __die "unknown implementation '$implementation'"
esac
