#!/bin/sh

set -eu

root=$(realpath $(dirname "$0")/..)

if [ $# -lt 1 ]; then
    echo "Usage: $0 <version>" >&2
    exit 1
fi

version=$1
uri="https://www.unicode.org/Public/${version}/ucd/UCD.zip"
dirpath=$root/tungsten-text/data/ucd

trap "rm -rf /tmp/ucd /tmp/ucd.zip" EXIT

curl -sSfL -o /tmp/ucd.zip $uri
rm -rf /tmp/ucd
mkdir /tmp/ucd
unzip -q -d /tmp/ucd /tmp/ucd.zip

rm -rf $dirpath
mkdir -p $dirpath
echo $version >$dirpath/version
mv /tmp/ucd/UnicodeData.txt $dirpath/
