(in-package :system)

(defun %count-file-descriptors ()
  (let* ((directory #p"/proc/self/fd/")
         (wild-path (make-pathname :name :wild :defaults directory))
         (entries (directory wild-path)))
    (length entries)))

(defun %memory-usage ()
  (let ((page-size (sysconf :sc-pagesize))
        (values
          (do* ((path #p"/proc/self/statm")
                (string (read-file-string path :external-format :ascii))
                (start 0)
                (end (or (position #\Newline string) (length string)))
                (values (make-array 0 :element-type 'integer
                                      :adjustable t :fill-pointer 0)))
               ((>= start end)
                values)
            (let* ((space (position #\Space string :start start))
                   (value-end (or space end))
                   (value (parse-integer string :start start :end value-end)))
              (vector-push-extend value values)
              (setf start (1+ value-end))))))
    (let ((virtual (* (aref values 0) page-size))
          (resident (* (aref values 1) page-size))
          (shared (* (aref values 2) page-size)))
      (values virtual resident shared))))
