(defpackage :postgresql
  (:use :cl)
  (:export
   #:protocol-error
   #:backend-error
   #:backend-error-l10n-severity
   #:backend-error-severity
   #:backend-error-code
   #:backend-error-message
   #:backend-error-detail
   #:backend-error-position
   #:backend-error-internal-position
   #:backend-error-internal-query
   #:backend-error-where
   #:backend-error-schema
   #:backend-error-table
   #:backend-error-column
   #:backend-error-data-type
   #:backend-error-constraint
   #:backend-error-file
   #:backend-error-line
   #:backend-error-routine

   #:codec-type
   #:oid
   #:unknown-codec
   #:unknown-codec-type
   #:unknown-codec-oid
   #:unencodable-value
   #:unencodable-value-value
   #:value-decoding-error
   #:value-decoding-error-octets
   #:codec
   #:codec-type
   #:codec-oid
   #:codec-encoding-function
   #:codec-decoding-function
   #:find-codec
   #:register-codec
   #:delete-codec
   #:encode-value
   #:decode-value

   #:*client*
   #:*connection-acquisition-timeout*
   #:missing-password
   #:unsupported-authentication-scheme
   #:unsupported-authentication-scheme-name
   #:unexpected-message
   #:unexpected-message-message
   #:no-available-connection
   #:client
   #:client-host
   #:client-port
   #:clinet-user
   #:client-password
   #:client-database
   #:client-application-name
   #:client-max-connections
   #:make-client
   #:close-client-connections
   #:with-client
   #:query/simple
   #:query))
